#!/bin/bash

# 2nd line will be filtered out
>&2 echo "1639286950 test1"
>&2 echo "1639286950 WARN annmine.rs:571 [3] Error uploading ann batch to http://4.ah.pktpool.io/submit: "
>&2 echo "1639081959 INFO annmine.rs:524 472 Ke/s   9.02Mb/s    overflow: [573, 573, 0, 0, 2466]    uploading: [1851, 3158, 0, 0, 0]                    accept/reject/overload: [1842/0/0, 1223/0/0, 0/2048/0, 2452/0/0, 0/0/0]              - goodrate: [76%, 68%, 0%, 100%, 0%]"
>&2 echo "1639286950 test2"

# test for illegal utf8 characters, which will be ignored
>&2 echo -n -e '\xdf\xff'
